#!/usr/bin/env bash
# GPC3 scFv design -- run on a GPU machine with RFantibody installed.
# Generated by src/scfv_design_prep.py; do not hand-edit the hotspots,
# regenerate them so they stay tied to the patent scan.
set -euo pipefail

TARGET="target_patch273.pdb"
HOTSPOTS="[A267,A270,A273,A274,A277,A372,A373,A375,A376,A379,A380]"
NDESIGN="${NDESIGN:-200}"

# 1. backbone design: dock a VHH/scFv framework onto the epitope
poetry run python /opt/RFantibody/scripts/rfdiffusion_inference.py \
    --config-name antibody \
    antibody.target_pdb="$TARGET" \
    antibody.framework_pdb=framework.pdb \
    inference.ckpt_override_path=/opt/RFantibody/weights/RFdiffusion_Ab.pt \
    'ppi.hotspot_res='"$HOTSPOTS" \
    'antibody.design_loops=[L1:8-13,L2:7,L3:9-11,H1:7,H2:6,H3:5-13]' \
    inference.num_designs="$NDESIGN" \
    inference.output_prefix=out/backbones/design

# 2. sequence design on the docked backbones
poetry run python /opt/RFantibody/scripts/proteinmpnn_interface_design.py \
    -pdbdir out/backbones -outpdbdir out/seqs

# 3. structure prediction filter -- keep designs that fold as intended
poetry run python /opt/RFantibody/scripts/rf2_predict.py \
    input.pdb_dir=out/seqs output.pdb_dir=out/predicted

# 4. patent re-check on the surviving CDRs (runs anywhere, no GPU)
python3 ../src/patent_seq_similarity.py query --fasta out/predicted/cdrs.fasta
